import { ConnectButton } from '@rainbow-me/rainbowkit';
import { useAccount } from 'wagmi';
import styles from '../styles/Home.module.css';
import Head from 'next/head';
import '@rainbow-me/rainbowkit/styles.css';

// import { VehicleCertificateForm } from './components/VehicleCertificateForm';
// import { VehicleList } from './components/VehicleList';

const CONTRACT_ADDRESS = 'YOUR_DEPLOYED_CONTRACT_ADDRESS';

export default function Home() {
  const { isConnected } = useAccount();

  return (
    <div className={styles.container}>
      <Head>
        <title>TransferTrust App</title>
        <meta
          content='Generated by @rainbow-me/create-rainbowkit'
          name='description'
        />
        <link href='./logo.png' rel='icon' />
      </Head>
      <nav className='bg-white shadow-lg'>
        <div className='max-w-7xl mx-auto px-4 sm:px-6 lg:px-8'>
          <div className='flex justify-between h-16'>
            <div className='flex items-center'>
              <img
                src='../styles/images/logo.png'
                alt='TransferTrust Logo'
                className='h-8 w-8 mr-2'
              />
              <h1 className='text-2xl font-bold text-gray-900'>Logo here!</h1>
              <h3>Sell your car with TransferTrust</h3>
            </div>
            <div className='flex items-center'>
              <ConnectButton />
            </div>
          </div>
        </div>
      </nav>

      <main className='max-w-7xl mx-auto py-6 sm:px-6 lg:px-8'>
        {isConnected ? (
          <section className='grid grid-cols-1 gap-6'>
            <article className='bg-white shadow sm:rounded-lg p-6'>
              <h2 className='text-xl font-semibold mb-4'>✅ Shared to:</h2>
              <h2 className='text-xl font-semibold mb-4'>👤 John Doe</h2>
              {/* <VehicleCertificateForm contractAddress={CONTRACT_ADDRESS} /> */}
              <div className='flex'>
                <div className='flex flex-col justify-flex-start'>
                  <h2>💳 Price: </h2>
                </div>
                <div className='flex flex-col justify-flex-start '>
                  <br />
                  <input type='text' placeholder='Token ID' id='tokenID' />
                  <input type='text' placeholder='Price (in USCD)' id='price' />
                  <button
                    className='iekbcc0 iekbcc9 ju367v78 ju367v7t ju367v9i ju367vn ju367vei ju367vf3 ju367v16 ju367v1h ju367v2g ju367v8u _12cbo8i3 ju367v8r _12cbo8i4 _12cbo8i6'
                    onClick={() => {
                      const tokenID = document.getElementById('tokenID')
                        ?.value as string;
                      const price = document.getElementById('price')
                        ?.value as string;
                    }}
                  >
                    🧾 List for Sale
                  </button>
                </div>
                <div className='flex flex-col justify-flex-start '>
                  <br />
                  <button
                    className='iekbcc0 iekbcc9 ju367v78 ju367v7t ju367v9i ju367vn ju367vei ju367vf3 ju367v16 ju367v1h ju367v2g ju367v8u _12cbo8i3 ju367v8r _12cbo8i4 _12cbo8i6'
                    onClick={() => {}}
                  >
                    🔁 Sell the car
                  </button>
                </div>
              </div>
            </article>

            <div className='bg-white shadow sm:rounded-lg p-6'>
              <h2 className='text-xl font-semibold mb-4'>Your Vehicles</h2>
              {/* <VehicleList contractAddress={CONTRACT_ADDRESS} /> */}
            </div>
          </section>
        ) : (
          <div className='text-center py-12'>
            <h2 className='text-2xl font-semibold text-gray-900'>
              Please connect your wallet to use TransferTrust
            </h2>
            <p className='mt-2 text-gray-600'>
              Connect your wallet to create and manage vehicle certificates
            </p>
          </div>
        )}
      </main>
    </div>
  );
}
