import type { NextPage } from 'next';
import '@rainbow-me/rainbowkit/styles.css';
import { Router } from 'next/router';
import { ConnectButton } from '@rainbow-me/rainbowkit';
import { useAccount, useReadContract, useWriteContract } from 'wagmi';
import styles from '../styles/Home.module.css';
import Head from 'next/head';
import '@rainbow-me/rainbowkit/styles.css';

export default function Home() {
  const { isConnected } = useAccount();

  return (
    <div className={styles.container}>
      <Head>
        <title>TransferTrust App</title>
        <meta
          content='Generated by @rainbow-me/create-rainbowkit'
          name='description'
        />
        <link href='./logo.png' rel='icon' />
      </Head>
      <nav className='bg-white shadow-lg'>
        <div className='max-w-7xl mx-auto px-4 sm:px-6 lg:px-8'>
          <div className='flex justify-between h-16'>
            <div className='flex items-center'>
              <img
                src='../styles/images/logo.png'
                alt='TransferTrust Logo'
                className='h-8 w-8 mr-2'
              />
              <div className='hidden md:block'>
                <div className='ml-10 flex items-baseline space-x-4'>
                  <a
                    href='/'
                    className='text-gray-900 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium'
                  >
                    Home
                  </a>
                  <a
                    href='/certificate'
                    className='text-gray-900 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium'
                  >
                    Certificate
                  </a>
                  <a
                    href='/main'
                    className='text-gray-900 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium'
                  ></a>
                  <a
                    href='/sale'
                    className='text-gray-900 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium'
                  >
                    Sale
                  </a>
                </div>
              </div>
            </div>
            <div className='flex items-center'>
              <ConnectButton />
            </div>
          </div>
        </div>
      </nav>

      <main className='max-w-7xl mx-auto py-6 sm:px-6 lg:px-8'>
        {isConnected ? (
          <div className='grid grid-cols-1 gap-6'>
            <div className='col-span-1 bg-white shadow overflow-hidden sm:rounded-lg'>
              <div className='px-4 py-5 sm:p-6'>
                <h3 className='text-lg leading-6 font-medium text-gray-900'>
                  Shared Data
                </h3>
                <div className='mt-2 max-w-xl text-sm text-gray-500'>
                  <p>
                    This is the data shared between the seller and{' '}
                    <buyer className='text-red-500'></buyer>
                  </p>
                </div>
              </div>
            </div>
          </div>
        ) : (
          <div className='grid grid-cols-1 gap-6'>
            <div className='col-span-1 bg-white shadow overflow-hidden sm:rounded-lg'>
              <div className='px-4 py-5 sm:p-6'>
                <h3 className='text-lg leading-6 font-medium text-gray-900'>
                  Shared Data
                </h3>
                <div className='mt-2 max-w-xl text-sm text-gray-500'>
                  <p>
                    This is the data shared between the seller and{' '}
                    <buyer className='text-red-500'></buyer>
                  </p>
                </div>
              </div>
            </div>
          </div>
        )}
      </main>
    </div>
  );
}
